### ISSUE TITLE
install does not work node 10 - 14 on windows 10

### ISSUE THREAD

**Issue by Ragers** [GenesisGateway/genesis.js#4]
This package does not work on any version of node 10+ to 14 on windows 10.

This is the last few lines and error being thrown when trying to just do `npm install genesis.js`

```
> cake build

events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/.bin/coffee ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11

Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:253:12)
    at onErrorNT (internal/child_process.js:429:16)
    [... lines matching original stack trace ...]

npm WARN ws@7.4.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\glob-watcher\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! genesis.js@2.0.5 install: `cake build`
npm ERR! Exit status 1
```

**Comment by darrenbarklie** [comment]
I encountered the same issue on macOS / Node v14.15.4 / npm 7.9.0 :

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! code 1
npm ERR! path ...[snip]/genesis.js
npm ERR! command failed
npm ERR! command sh -c cake build
npm ERR! events.js:292
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR! 
npm ERR! Error: spawn node_modules/.bin/coffee ENOENT
npm ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
npm ERR!     at onErrorNT (internal/child_process.js:465:16)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! 
npm ERR! Emitted 'error' event on ChildProcess instance at:
npm ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR!     at onErrorNT (internal/child_process.js:465:16)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR!  {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawn node_modules/.bin/coffee',
npm ERR!   path: 'node_modules/.bin/coffee',
npm ERR!   spawnargs: [ '-c', '-o', 'lib', 'src' ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     ...[snip]/.npm/_logs/2021-05-04T17_29_01_558Z-debug.log
```

**Comment by dyd** [comment]
Hello @darrenbarklie and @Ragers
We have a new release [2.1.0](https://github.com/GenesisGateway/genesis.js/releases/tag/2.1.0)
It doesn't solve the **npm install genesis.js**. As an alternative way of using the lib you can do the following:

* Navigate to <your project> folder
* Execute `npm install -g genesis.js`
* Execute `npm link genesis.js`

We will notify you when the `npm install genesis.js` is available.

**Comment by dyd** [comment]
Hello @darrenbarklie  and @Ragers 
We have a new release [2.1.1](https://github.com/GenesisGateway/genesis.js/releases/tag/2.1.1)

Also, feel free to use `npm install genesis.js`.

We are closing this one. If you have any issues feel free to post a new issue.
